# Generated by Django 2.0.3 on 2018-03-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('criteria', models.DecimalField(decimal_places=2, max_digits=2)),
                ('requirement', models.TextField(max_length=260)),
            ],
        ),
    ]
