# Generated by Django 2.0.3 on 2018-03-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='criteria',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
